version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - JWT_SECRET=your_jwt_secret # Replace this with an environment variable or use a .env file
    volumes:
      - .:/usr/src/app
